name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Install activitywatch
      run: |
        curl https://api.github.com/repos/ActivityWatch/activitywatch/releases/latest \
             | grep browser_download_url \
             | grep linux \
             | cut -d '"' -f 4 \
             | wget -qi -
        unzip activitywatch*
        ./activitywatch/aw-qt
    - name: Test with pytest
      env:
        XDG_DATA_DIRS: none
      run: |
        tox
